---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-test
  namespace: test
  annotations:
    test-key: test-value
spec:
  template:
    spec:
      containers:
      - command:
        - "date"
        image: ubuntu:latest
        name: example-test
      restartPolicy: Never
---
